### PR TITLE
Fixes #57 using un-modifyable lists & judicious synchronization

### LINKED ISSUE #57: scalatest threadsafe?
We are currently using scalatest in Maven with a parallel build, this will lead to Maven warning about threadsafety:

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in labeler:
[WARNING] org.scalatest:scalatest-maven-plugin:2.0.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************

Did anyone already experiment with this in multithreaded build (e.g. using -T1C option with mvn)? Or can we simply ignore this warning?

### PR DESCRIPTION
**Pull request by chrisalbright**
Mostly just ensuring lists are un-modifyable. Added synchronization to the side-effect code which creates a directory if it doesn't exist. Not sure how to test this, but in the build that inspired this change, the warnings are gone, and all is well.

### CODE REVIEW

**Comment by chrisalbright** [comment]
Hi there... any thoughts on merging this?

**Comment by rdefreitas** [comment]
looks good to me. I'm not sure who has write access here. maybe @gcberger / @cheeseng ?

**Comment by rdefreitas** [comment]
@chrisalbright looks like you have a merge conflict, not sure if you saw that come up

**Comment by chrisalbright** [comment]
@rdefreitas thanks for the head's up. I don't recall seeing this when I opened the PR, but it should be ok now.

**Comment by chrisalbright** [comment]
Hello out there! Is anybody interested in this project any longer? @gcberger ? @cheeseng

**Comment by chrisalbright** [comment]
@rdefreitas do you have any ideas on how I can help move this forward? Is this project abandoned?

**Comment by bvenners** [comment]
@chrisalbright not abandoned, just moving in a bit of slow motion. @katrinsharp has been working on it lately, and we should have a release soon.

**Comment by chrisalbright** [comment]
Hi, @bvenners and @katrinsharp - just checking in here. Any motion on this PR?

**Comment by katrinsharp** [comment]
@chrisalbright yes today.

**Comment by katrinsharp** [comment]
LGTM.

**Pull request merged**
