### PR TITLE
Respect JAVA_HOME environment variable

### LINKED ISSUE #26: Forked process don't respect JAVA_HOME when calling java
With _forkMode_ set to _once_ or _always_ new processes are forked to execute the tests. They start java using the command _java_, but in the maven ecosystem one would expect the forked processes to use $JAVA_HOME/bin/java instead. This would ensure that the same java version is used as for the build as for the test execution.

You can see the following line in your maven output when run with -X option (values in ??? are replaced with what they represent)
`[14:07:24][???groupdId:artifactId???] [DEBUG] Forking ScalaTest via: /bin/sh -c cd ???basedir??? && java -Dbasedir=???basedir??? org.scalatest.tools.Runner -R '???basedir???/target/classes ???basedir???/target/test-classes' -o -u ???basedir???/target/surefire-reports/`

but would expect the following

`[14:07:24][???groupdId:artifactId???] [DEBUG] Forking ScalaTest via: /bin/sh -c cd ???basedir??? && $JAVA_HOME/bin/java -Dbasedir=???basedir??? org.scalatest.tools.Runner -R '???basedir???/target/classes ???basedir???/target/test-classes' -o -u ???basedir???/target/surefire-reports/`

A typical symptom of this is the following error message:
`Unsupported major.minor version 52.0`

This happens if your java code is compiled with Java 8 and then executed with Java <8. Other combinations of Java versions will lead to slightly different error messages.

### PR DESCRIPTION
**Pull request by andreoss**
Closes #26, also related to #6

### CODE REVIEW

**Comment by katrinsharp** [comment]
Hi @andreoss. How is your PR different from https://github.com/scalatest/scalatest-maven-plugin/pull/43 ? Thank you.

**Comment by cstroe** [comment]
@katrinsharp This PR does an additional explicit lookup for the `JAVA_HOME` environment variable if the `java.home` system property is not set.

@andreoss To my knowledge, looking at the `JAVA_HOME` environment variable is not required.  The `java.home` system property is [always set by the JVM](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html), so if your JVM program is running, the location of the JVM should be available from the `java.home`, no need to look elsewhere.

Maven launcher scripts handle `JAVA_HOME` to find which JVM to execute, but once scala-maven-plugin is launched, it should only look at the `java.home` system property.

**Comment by cstroe** [comment]
As it was mentioned in another PR, we should be using Toolchain lookups: https://github.com/scalatest/scalatest-maven-plugin/pull/43#issuecomment-439405249

**Comment by andreoss** [comment]
> @andreoss To my knowledge, looking at the `JAVA_HOME` environment variable is not required. The `java.home` system property is [always set by the JVM](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html), so if your JVM program is running, the location of the JVM should be available from the `java.home`, no need to look elsewhere.
> 
> Maven launcher scripts handle `JAVA_HOME` to find which JVM to execute, but once scala-maven-plugin is launched, it should only look at the `java.home` system property.

You might be right. But surefire seems to query for `JAVA_HOME` before `java.home`
https://github.com/apache/maven-surefire/blob/master/surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncher.java#L77
My guess is that this approach is chosen because it's less bug-prone, since `System` properties is a mutable collection, and value for `java.home` can be altered. Unlike immutable environment variables.

Also there could be cases when using that the same JVM which was used for maven is not always desirable. The standard `mvn` script seems to always set `JAVA_HOME`, but in case maven was started from IDE it may not be so.

**Comment by cstroe** [comment]
@andreoss Yep, it doesn't hurt to use `JAVA_HOME` as a backup as far as I know.

**Comment by katrinsharp** [comment]
LGTM

**Comment by cerveada** [comment]
Hello, there seems to be some confusion

> You might be right. But surefire seems to query for JAVA_HOME before java.home
> https://github.com/apache/maven-surefire/blob/master/surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncher.java#L77

This is **an integration test** code, not code used by surefire itself. In fact surefire uses `java.home`. I can share a link to simple project that I used to test that if anyone is interested.

> @andreoss Yep, it doesn't hurt to use JAVA_HOME as a backup as far as I know. 👍

But that is not what is done in the PR.  `JAVA_HOME` is the defualt and the `java.home` is a backup.

Please take a look at #80 where I described why it seems to me the default should be `java.home`.

**Pull request merged**
